services:
  gaaf-db:
    image: mysql:8.4
    container_name: gaaf_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gaaf
      MYSQL_DATABASE: db_gaaf
    ports:
      - "3306:3306"
    volumes:
      - gaaf_db:/var/lib/mysql
    networks:
      - gaaf-net

  auth-db:
	image: mongo
	container_name: auth-db
	restart: always
	command: ["--replSet", "rs0"]
	ports:
	  - "27017:27017"
	volumes:
	  - gaaf_auth_db:/data/db
	networks:
	  - gaaf-net



volumes:
  gaaf_db:
  gaaf_auth_db:

networks: 
  gaaf-net:
    driver: bridge
